services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=big-data
    env_file:
      - ./hadoop.env
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    ports:
      - 8032:8032
      - 8031:8031
      - 8030:8030
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    ports:
      - 19888:19888
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
  # flume:
  #   image: flume-hdfs:logs
  #   container_name: flume
  #   restart: always
  #   environment:
  #     - HDFS_PATH=hdfs://namenode:9000/user/hadoopuser/project/logs
  #     - LOG_INTERVAL=0.5
  #     - AGENT_NAME=agent
  #   env_file:
  #     - ./hadoop.env
  #   depends_on:
  #     - namenode
  sqoop:
    image: sqoop:mysql
    container_name: sqoop
    restart: always
    ports:
      - 12000:12000
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sqoopdb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    depends_on:
      - sqoop
  # mapreduce:
  #   image: mapreduce:logs
  #   container_name: mapreduce
  #   restart: always
  #   environment:
  #     HDFS_INPUT: "/user/hadoopuser/project/logs"
  #     JOB_TYPE: level
  #     SERVICE_PRECONDITION: "namenode:9000 namenode:9870 resourcemanager:8088"
  #   env_file:
  #     - ./hadoop.env
  #   depends_on:
  #     - namenode

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
