FROM bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8

RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list && \
    sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    sed -i '/stretch-updates/d' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --allow-unauthenticated python3 && \
    rm -rf /var/lib/apt/lists/*
